camera_ID ='14366960';
camera_model_dir = '/Users/shcen/code/sensor-models/cameras/bumblebee2';


% load camera model
camera_lut= Monolithic(strcat(camera_model_dir,'/BB2-',camera_ID,'-512x384-Model.monolithic'));
left_sensor = JavaPbBilinearLUTCameraModelToMatlab(camera_lut{1});
right_sensor = JavaPbBilinearLUTCameraModelToMatlab(camera_lut{2});

% create Camera Model
baseline = right_sensor.G_camerabase_cameraimage(2,4);
left = struct('fx', left_sensor.focal_length_x, ...
    'fy', left_sensor.focal_length_y,...
    'cx', left_sensor.principal_point_x,...
    'cy', left_sensor.principal_point_y,...  
    'lut',left_sensor.bilinear_lut_xy) ;
right = struct('fx', right_sensor.focal_length_x, ...
    'fy', right_sensor.focal_length_y,...
    'cx', right_sensor.principal_point_x,...
    'cy', right_sensor.principal_point_y,...  
    'lut',right_sensor.bilinear_lut_xy) ;

camera_model = struct('baseline',baseline,'left',left,'right',right);
save(strcat('BB2-',camera_ID,'.mat'), 'camera_model') ;